version: '3.1'
services:
  db:
    image: postgres:10-alpine
    volumes:
      - "./data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: dontGoThere
